### ISSUE TITLE
Finish hardware readme

### ISSUE THREAD

**Issue by sparklestheunicorn** [FourThievesVinegar/solderless-microlab#25]
There is currently a partial README.md file in the hardware directory of the project. This needs to be updated with:
- A complete list of parts (specs, manufacturer numbers, where to get them etc.). This includes types of syringes, tubes, printing recommendations, and all electronics. Preferably with pics.
- A complete list of assembly steps with pics.
- If anyone has a completed prototype and can provide any specs, that would be awesome!

**Comment by myrinzic** [comment]
Leantime ticket #111

**Comment by myrinzic** [comment]
Leantime Ticket 111

**Comment by sparklestheunicorn** [comment]
This is largely complete (more details and pics are required in docs/operation.md). Separate issues can be made for updating particular parts of the documentation.
