### ISSUE TITLE
Recipe details and descriptions

### ISSUE THREAD

**Issue by sparklestheunicorn** [FourThievesVinegar/solderless-microlab#27]
It would be nice for users if recipes had an ingredients list, and a short description so users can orient themselves before recipe preparation. Something like:

name: "aspirin"
ingredients: ["2.0 g salicylic acid", "XX mL acetic anhydride", "XX mL H2SO4"]
description: "A common pain reliever originally derived from willow bark."

This would also require a /details/<name> backed API end point (or equivalent) that returns details for a particular recipe.

To consider: do we also want to include common dosage and effect information?

**Comment by myrinzic** [comment]
Leantime Ticket 109

**Comment by sparklestheunicorn** [comment]
This is complete
