### ISSUE TITLE
Two important links dead on setup and operation page 

### ISSUE THREAD

**Issue by abstractzwieback** [FourThievesVinegar/solderless-microlab#278]
On the [setting up and operating the microlab](https://github.com/FourThievesVinegar/solderless-microlab/blob/master/docs/operation.md) page the two below links are dead. I don’t know the project well enough to know what these are meant to point to. 

[Control Unit](https://github.com/FourThievesVinegar/solderless-microlab/blob/master/docs/assembly-control-unit)
[MicroLab Cables](https://github.com/FourThievesVinegar/solderless-microlab/blob/master/docs/assembly-control-unit#cables)

**Comment by sparklestheunicorn** [comment]
Thanks for reporting this. It should be fixed now :+1:
