### ISSUE TITLE
PARTS: CU-RLY 4 Channel Relay Board is listed twice in the parts list

### ISSUE THREAD

**Issue by pablo-01** [FourThievesVinegar/solderless-microlab#294]
Hi, I'm starting with control unit. Got all the printable parts ready and now ordering parts from the list. 

CU-RLY: '4 Channel Relay Board' is listed twice in the Control Unit section - do I need two of them or is this a mistake? 

Thanks.

**Comment by phaseloop** [comment]
It's most likely a mistake.
