### ISSUE TITLE
Create hardware testing endpoints

### ISSUE THREAD

**Issue by sparklestheunicorn** [FourThievesVinegar/solderless-microlab#39]
Currently the backend doesn't have endpoints for testing relays or stepper motors. As a developer and user I would like them to exist.

Acceptance criteria:
- There exist endpoints on the python service to:
  - Test each of the relays one at a time
  - Test each of the motors one at a time
  - Test all of the relays in sequence
  - Test all of the motors in sequence
  - Get the thermometer temperature
  - Activate the stirrer (or is this just one of the motors?)

**Comment by myrinzic** [comment]
Leantime Ticket 101

**Comment by sparklestheunicorn** [comment]
This is now handled by using a built-in test recipe
