### ISSUE TITLE
BACKEND: Backend keeps going after simulated recipe completes

### ISSUE THREAD

**Issue by sparklestheunicorn** [FourThievesVinegar/solderless-microlab#48]
When I complete the aspirin experiment using the test celery configuration, I see the backend daemon continue doing things. The gui gets 500 errors when this is happening. The status reverts to "running" after being "complete" for 2 polls.

This is happening in the simulation environment and seems to be related to heating steps.

![image](https://user-images.githubusercontent.com/2106250/123562534-439a4680-d77d-11eb-9239-21d08b89c950.png)

**Comment by myrinzic** [comment]
Leantime Ticket 100

**Comment by 0phelia36** [comment]
This was fixed at some point I think, and shouldn't be possible now in any case now that celery has been removed.
