### ISSUE TITLE
UI: Show status for individual steps

### ISSUE THREAD

**Issue by sparklestheunicorn** [FourThievesVinegar/solderless-microlab#59]
As a microlab user, I want to know what's happening with the microlab when I'm running a reaction. I want to have a timer that counts down the remaining time in my step. I want to know the temperature (for example) when the heat is being adjusted.

Acceptance Criteria:
- There is a temperature readout on the status page
- There is a countdown when the steps are timed

**Comment by myrinzic** [comment]
Leantime Ticket 29?

**Comment by sparklestheunicorn** [comment]
This is now supported.
