### ISSUE TITLE
Enable recipes to be written in more accessible formats and imported

### ISSUE THREAD

**Issue by sparklestheunicorn** [FourThievesVinegar/solderless-microlab#60]
Writing python classes is cumbersome and requires specialized knowledge. More accessible formats like markdown or csv would make recipe creation easier for end users, especially non-technical folks.

- [ ] Investigate formatting options and decide on reasonable formats (JSON?)
- [ ] Write functionality to import recipes from these formats
- [ ] Update Apothecarium to export the new format

**Comment by myrinzic** [comment]
Leantime Ticket 96

**Comment by sparklestheunicorn** [comment]
These are now JSON
