### ISSUE TITLE
Write startup scripts

### ISSUE THREAD

**Issue by sparklestheunicorn** [FourThievesVinegar/solderless-microlab#62]
We need scripts to run the backend and gui on startup on the pi.

- They should run at startup and start the GUI in fullscreen mode.
- If there are errors, they should raise them to the user in understandable ways.
 - Ideally we would recover gracefully.

**Comment by myrinzic** [comment]
Leantime Ticket 95

**Comment by sparklestheunicorn** [comment]
Startup scripts exist and the production disk image runs everything at boot and user login
