### ISSUE TITLE
Make a Disk Image

### ISSUE THREAD

**Issue by sparklestheunicorn** [FourThievesVinegar/solderless-microlab#63]
As a beta user, I want an easy experience setting up the microlab.

This is dependent on other beta Release issues being completed.

The image should start up auto-magically when the RPi is turned on with no configuration required.

The image should be uploaded to a public URL.

**Comment by myrinzic** [comment]
Leantime Ticket 93

**Comment by sparklestheunicorn** [comment]
Disk images are made and seeding
