### ISSUE TITLE
PARTS: Manifold needs a hole for the temperature probe.

### ISSUE THREAD

**Issue by sparklestheunicorn** [FourThievesVinegar/solderless-microlab#74]
Currently there's no dedicated hole in the manifold for the temperature probe. Its already tight jamming the temp control tube into the manifold top, so we could use a dedicated place for it.

**Comment by myrinzic** [comment]
Leantime Ticket 92

**Comment by sparklestheunicorn** [comment]
> > Currently there's no dedicated hole in the manifold for the temperature probe. Its already tight jamming the temp control tube into the manifold top, so we could use a dedicated place for it.
> 
> create a special repository and store it there

We do have a parts repo: https://github.com/FourThievesVinegar/Parts/tree/master/v5 - What we need is an updated CAD file for the parts that includes this new hole.

**Comment by sparklestheunicorn** [comment]
The v0.6 manifold core has many more holes than the previous reactor design. This is complete.
