### ISSUE TITLE
PARTS: Re-CAD and migrate to 3MF/STEP from STL for hardware files

### ISSUE THREAD

**Issue by 0x42red** [FourThievesVinegar/solderless-microlab#83]
Currently we use STL files for the 3d files.  We should export a 3MF version of the file for use instead.  With 3MF units of measurement are baked into the format so reproductions should be more accurate as well as some other features that might matter to the project in the future.

https://www.3dnatives.com/en/stl-vs-3mf-280620224/

**Comment by 0x42red** [comment]
@sparklestheunicorn in the log it looks like you made the last change to the STL.  Do we have access to the CAD project files still?  Would that make sense to also put them in the repo?

**Comment by myrinzic** [comment]
Leantime Ticket 91

**Comment by sparklestheunicorn** [comment]
Alas we do not have access to the original CAD files - they will need to be re-cadded.

**Comment by sparklestheunicorn** [comment]
Parts have been re-cadded and [we now have](https://github.com/FourThievesVinegar/microlab-parts/tree/master/v5) both STL and STEP files
